#!/usr/bin/env perl
use strict;
use warnings;
use JSON::PP qw(decode_json);
use Getopt::Long qw(GetOptions);
use File::Basename qw(basename);
use File::Path qw(make_path);

my $format = 'bash';
my $out_dir = 'src/cmd/completions/bash';
my $help = 0;
my $skip_fail = 0;

GetOptions(
    'format=s'  => \$format,
    'out-dir=s' => \$out_dir,
    'help'      => \$help,
    'skip-fail' => \$skip_fail,
) or usage();

usage() if $help;

if ($format ne 'bash') {
    die "unsupported format: $format\n";
}

my @tools = @ARGV;
if (!@tools) {
    usage();
}

make_path($out_dir);

for my $tool (@tools) {
    my $json = qx{"$tool" --dump-syntax};
    if ($? != 0) {
        if ($skip_fail) {
            warn "skipping $tool: --dump-syntax failed\n";
            next;
        }
        die "failed to run $tool --dump-syntax\n";
    }

    my $data = decode_json($json);
    my $tool_name = basename($tool);
    my $out_file = "$out_dir/$tool_name.bash";

    open my $fh, '>', $out_file or die "open $out_file: $!\n";
    print $fh "# Generated by generate_completions.pl --format bash\n";
    print $fh "# Source this file to enable completions for $tool_name\n\n";

    my $func = "_openafs_${tool_name}";
    print $fh "$func() {\n";
    print $fh '    local cur="${COMP_WORDS[COMP_CWORD]}"' . "\n";

    my $no_opcodes = $data->{options}->{no_opcodes} ? 1 : 0;
    my @commands = @{$data->{commands} || []};

    if ($no_opcodes) {
        my $opts = join(' ', options_for_command($commands[0]));
        print $fh '    COMPREPLY=( $(compgen -W "' . $opts . '" -- "$cur") )' . "\n";
        print $fh "    return\n";
    } else {
        my @visible_cmds = grep { is_visible_command($_) } @commands;
        my $cmd_words = join(' ', map { $_->{command} } @visible_cmds);
        print $fh '    if [[ $COMP_CWORD -eq 1 ]]; then' . "\n";
        print $fh '        COMPREPLY=( $(compgen -W "' . $cmd_words . '" -- "$cur") )' . "\n";
        print $fh "        return\n";
        print $fh "    fi\n\n";
        print $fh '    local sub="${COMP_WORDS[1]}"' . "\n";
        print $fh '    case "$sub" in' . "\n";

        for my $cmd (@visible_cmds) {
            my $opts = join(' ', options_for_command($cmd));
            my $name = $cmd->{command};
            print $fh "        $name)\n";
            if ($opts ne '') {
                print $fh '            COMPREPLY=( $(compgen -W "' . $opts . '" -- "$cur") )' . "\n";
            } else {
                print $fh "            COMPREPLY=()\n";
            }
            print $fh "            ;;\n";
        }
        print $fh "    esac\n";
    }

    print $fh "}\n";
    print $fh "complete -F $func $tool_name\n";
    close $fh;
}

sub usage {
    die "usage: generate_completions.pl --format bash --out-dir DIR [--skip-fail] <tool>...\n";
}

sub is_visible_command {
    my ($cmd) = @_;
    return 0 if $cmd->{hidden};
    return 0 if $cmd->{implicit};
    return 0 if !defined $cmd->{command};
    return 0 if $cmd->{command} eq '';
    return 0 if $cmd->{command} =~ /^-/;
    return 1;
}

sub options_for_command {
    my ($cmd) = @_;
    return () if !$cmd || !$cmd->{parameters};
    my @out;
    for my $p (@{$cmd->{parameters}}) {
        next if $p->{hidden};
        next if !$p->{name};
        next if $p->{name} !~ /^-/;
        push @out, $p->{name};
        if ($p->{aliases} && ref($p->{aliases}) eq 'ARRAY') {
            push @out, @{$p->{aliases}};
        }
    }
    return @out;
}
