# Generated by generate_completions.pl --format bash
# Source this file to enable completions for bos

_openafs_bos() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "addhost addkey adduser create delete exec getdate getlog getrestart getrestricted install listhosts listkeys listusers prune removehost removekey removeuser restart salvage setauth setcellname setrestart setrestricted shutdown start startup status stop uninstall" -- "$cur") )
        return
    fi

    local sub="${COMP_WORDS[1]}"
    case "$sub" in
        addhost)
            COMPREPLY=( $(compgen -W "-server -host -clone -cell -noauth -localauth -help" -- "$cur") )
            ;;
        addkey)
            COMPREPLY=( $(compgen -W "-server -key -kvno -cell -noauth -localauth -help" -- "$cur") )
            ;;
        adduser)
            COMPREPLY=( $(compgen -W "-server -user -cell -noauth -localauth -help" -- "$cur") )
            ;;
        create)
            COMPREPLY=( $(compgen -W "-server -instance -type -cmd -notifier -cell -noauth -localauth -help" -- "$cur") )
            ;;
        delete)
            COMPREPLY=( $(compgen -W "-server -instance -cell -noauth -localauth -help" -- "$cur") )
            ;;
        exec)
            COMPREPLY=( $(compgen -W "-server -cmd -cell -noauth -localauth -help" -- "$cur") )
            ;;
        getdate)
            COMPREPLY=( $(compgen -W "-server -file -dir -cell -noauth -localauth -help" -- "$cur") )
            ;;
        getlog)
            COMPREPLY=( $(compgen -W "-server -file -cell -noauth -localauth -help" -- "$cur") )
            ;;
        getrestart)
            COMPREPLY=( $(compgen -W "-server -cell -noauth -localauth -help" -- "$cur") )
            ;;
        getrestricted)
            COMPREPLY=( $(compgen -W "-server -cell -noauth -localauth -help" -- "$cur") )
            ;;
        install)
            COMPREPLY=( $(compgen -W "-server -file -dir -cell -noauth -localauth -help" -- "$cur") )
            ;;
        listhosts)
            COMPREPLY=( $(compgen -W "-server -cell -noauth -localauth -help" -- "$cur") )
            ;;
        listkeys)
            COMPREPLY=( $(compgen -W "-server -showkey -cell -noauth -localauth -help" -- "$cur") )
            ;;
        listusers)
            COMPREPLY=( $(compgen -W "-server -cell -noauth -localauth -help" -- "$cur") )
            ;;
        prune)
            COMPREPLY=( $(compgen -W "-server -bak -old -core -all -cell -noauth -localauth -help" -- "$cur") )
            ;;
        removehost)
            COMPREPLY=( $(compgen -W "-server -host -cell -noauth -localauth -help" -- "$cur") )
            ;;
        removekey)
            COMPREPLY=( $(compgen -W "-server -kvno -cell -noauth -localauth -help" -- "$cur") )
            ;;
        removeuser)
            COMPREPLY=( $(compgen -W "-server -user -cell -noauth -localauth -help" -- "$cur") )
            ;;
        restart)
            COMPREPLY=( $(compgen -W "-server -instance -bosserver -all -cell -noauth -localauth -help" -- "$cur") )
            ;;
        salvage)
            COMPREPLY=( $(compgen -W "-server -partition -volume -file -all -showlog -parallel -tmpdir -orphans -forceDAFS -salvagedirs -cell -noauth -localauth -help" -- "$cur") )
            ;;
        setauth)
            COMPREPLY=( $(compgen -W "-server -authrequired -cell -noauth -localauth -help" -- "$cur") )
            ;;
        setcellname)
            COMPREPLY=( $(compgen -W "-server -name -cell -noauth -localauth -help" -- "$cur") )
            ;;
        setrestart)
            COMPREPLY=( $(compgen -W "-server -time -general -newbinary -cell -noauth -localauth -help" -- "$cur") )
            ;;
        setrestricted)
            COMPREPLY=( $(compgen -W "-server -mode -cell -noauth -localauth -help" -- "$cur") )
            ;;
        shutdown)
            COMPREPLY=( $(compgen -W "-server -instance -wait -cell -noauth -localauth -help" -- "$cur") )
            ;;
        start)
            COMPREPLY=( $(compgen -W "-server -instance -cell -noauth -localauth -help" -- "$cur") )
            ;;
        startup)
            COMPREPLY=( $(compgen -W "-server -instance -cell -noauth -localauth -help" -- "$cur") )
            ;;
        status)
            COMPREPLY=( $(compgen -W "-server -instance -long -cell -noauth -localauth -help" -- "$cur") )
            ;;
        stop)
            COMPREPLY=( $(compgen -W "-server -instance -wait -cell -noauth -localauth -help" -- "$cur") )
            ;;
        uninstall)
            COMPREPLY=( $(compgen -W "-server -file -dir -cell -noauth -localauth -help" -- "$cur") )
            ;;
    esac
}
complete -F _openafs_bos bos
