# Generated by generate_completions.pl --format bash
# Source this file to enable completions for fs

_openafs_fs() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "bypassthreshold checkservers checkvolumes cleanacl copyacl discon diskfree examine exportafs flush flushall flushmount flushvolume getcacheparms getcalleraccess getcellstatus getclientaddrs getcrypt getfid getserverprefs listacl listaliases listcells listquota lsmount messages mkmount newalias newcell nukenfscreds precache quota rmmount rxstatpeer rxstatproc setacl setcachesize setcbaddr setcell setclientaddrs setcrypt setquota setserverprefs setvol storebehind sysname uuid whereis whichcell wscell" -- "$cur") )
        return
    fi

    local sub="${COMP_WORDS[1]}"
    case "$sub" in
        bypassthreshold)
            COMPREPLY=( $(compgen -W "-size -help" -- "$cur") )
            ;;
        checkservers)
            COMPREPLY=( $(compgen -W "-cell -all -fast -interval -help" -- "$cur") )
            ;;
        checkvolumes)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
        cleanacl)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        copyacl)
            COMPREPLY=( $(compgen -W "-fromdir -todir -clear -id -if -help" -- "$cur") )
            ;;
        discon)
            COMPREPLY=( $(compgen -W "-mode -policy -force -uid -help" -- "$cur") )
            ;;
        diskfree)
            COMPREPLY=( $(compgen -W "-path -human -help" -- "$cur") )
            ;;
        examine)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        exportafs)
            COMPREPLY=( $(compgen -W "-type -start -convert -uidcheck -submounts -clipags -pagcb -help" -- "$cur") )
            ;;
        flush)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        flushall)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
        flushmount)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        flushvolume)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        getcacheparms)
            COMPREPLY=( $(compgen -W "-files -excessive -help" -- "$cur") )
            ;;
        getcalleraccess)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        getcellstatus)
            COMPREPLY=( $(compgen -W "-cell -help" -- "$cur") )
            ;;
        getclientaddrs)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
        getcrypt)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
        getfid)
            COMPREPLY=( $(compgen -W "-path -literal -help" -- "$cur") )
            ;;
        getserverprefs)
            COMPREPLY=( $(compgen -W "-file -numeric -vlservers -help" -- "$cur") )
            ;;
        listacl)
            COMPREPLY=( $(compgen -W "-path -id -if -cmd -help" -- "$cur") )
            ;;
        listaliases)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
        listcells)
            COMPREPLY=( $(compgen -W "-numeric -help" -- "$cur") )
            ;;
        listquota)
            COMPREPLY=( $(compgen -W "-path -human -help" -- "$cur") )
            ;;
        lsmount)
            COMPREPLY=( $(compgen -W "-dir -help" -- "$cur") )
            ;;
        messages)
            COMPREPLY=( $(compgen -W "-show -help" -- "$cur") )
            ;;
        mkmount)
            COMPREPLY=( $(compgen -W "-dir -vol -cell -rw -fast -help" -- "$cur") )
            ;;
        newalias)
            COMPREPLY=( $(compgen -W "-alias -name -help" -- "$cur") )
            ;;
        newcell)
            COMPREPLY=( $(compgen -W "-name -servers -linkedcell -help" -- "$cur") )
            ;;
        nukenfscreds)
            COMPREPLY=( $(compgen -W "-addr -help" -- "$cur") )
            ;;
        precache)
            COMPREPLY=( $(compgen -W "-blocks -help" -- "$cur") )
            ;;
        quota)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        rmmount)
            COMPREPLY=( $(compgen -W "-dir -help" -- "$cur") )
            ;;
        rxstatpeer)
            COMPREPLY=( $(compgen -W "-enable -disable -clear -help" -- "$cur") )
            ;;
        rxstatproc)
            COMPREPLY=( $(compgen -W "-enable -disable -clear -help" -- "$cur") )
            ;;
        setacl)
            COMPREPLY=( $(compgen -W "-dir -acl -clear -negative -id -if -help" -- "$cur") )
            ;;
        setcachesize)
            COMPREPLY=( $(compgen -W "-blocks -reset -help" -- "$cur") )
            ;;
        setcbaddr)
            COMPREPLY=( $(compgen -W "-addr -help" -- "$cur") )
            ;;
        setcell)
            COMPREPLY=( $(compgen -W "-cell -suid -nosuid -help" -- "$cur") )
            ;;
        setclientaddrs)
            COMPREPLY=( $(compgen -W "-address -help" -- "$cur") )
            ;;
        setcrypt)
            COMPREPLY=( $(compgen -W "-crypt -help" -- "$cur") )
            ;;
        setquota)
            COMPREPLY=( $(compgen -W "-path -max -help" -- "$cur") )
            ;;
        setserverprefs)
            COMPREPLY=( $(compgen -W "-servers -vlservers -file -stdin -help" -- "$cur") )
            ;;
        setvol)
            COMPREPLY=( $(compgen -W "-path -max -offlinemsg -help" -- "$cur") )
            ;;
        storebehind)
            COMPREPLY=( $(compgen -W "-kbytes -files -allfiles -verbose -help" -- "$cur") )
            ;;
        sysname)
            COMPREPLY=( $(compgen -W "-newsys -help" -- "$cur") )
            ;;
        uuid)
            COMPREPLY=( $(compgen -W "-generate -help" -- "$cur") )
            ;;
        whereis)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        whichcell)
            COMPREPLY=( $(compgen -W "-path -help" -- "$cur") )
            ;;
        wscell)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
    esac
}
complete -F _openafs_fs fs
