# Generated by generate_completions.pl --format bash
# Source this file to enable completions for kas

_openafs_kas() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "create delete examine forgetticket interactive list listtickets noauthentication quit setfields setpassword statistics stringtokey unlock" -- "$cur") )
        return
    fi

    local sub="${COMP_WORDS[1]}"
    case "$sub" in
        create)
            COMPREPLY=( $(compgen -W "-name -initial_password -admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        delete)
            COMPREPLY=( $(compgen -W "-name -admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        examine)
            COMPREPLY=( $(compgen -W "-name -showkey -admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        forgetticket)
            COMPREPLY=( $(compgen -W "-all -help" -- "$cur") )
            ;;
        interactive)
            COMPREPLY=( $(compgen -W "-admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        list)
            COMPREPLY=( $(compgen -W "-long -showadmin -showkey -admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        listtickets)
            COMPREPLY=( $(compgen -W "-name -long -help" -- "$cur") )
            ;;
        noauthentication)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
        quit)
            COMPREPLY=( $(compgen -W "-help" -- "$cur") )
            ;;
        setfields)
            COMPREPLY=( $(compgen -W "-name -flags -expiration -lifetime -pwexpires -reuse -attempts -locktime -admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        setpassword)
            COMPREPLY=( $(compgen -W "-name -new_password -kvno -admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        statistics)
            COMPREPLY=( $(compgen -W "-admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
        stringtokey)
            COMPREPLY=( $(compgen -W "-string -cell -help" -- "$cur") )
            ;;
        unlock)
            COMPREPLY=( $(compgen -W "-name -admin_username -password_for_admin -cell -servers -noauth -help" -- "$cur") )
            ;;
    esac
}
complete -F _openafs_kas kas
