# Generated by generate_completions.pl --format bash
# Source this file to enable completions for pts

_openafs_pts() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "adduser chown creategroup createuser delete examine interactive listentries listmax listowned membership quit removeuser rename setfields setmax sleep source" -- "$cur") )
        return
    fi

    local sub="${COMP_WORDS[1]}"
    case "$sub" in
        adduser)
            COMPREPLY=( $(compgen -W "-user -group -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        chown)
            COMPREPLY=( $(compgen -W "-name -owner -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        creategroup)
            COMPREPLY=( $(compgen -W "-name -owner -id -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        createuser)
            COMPREPLY=( $(compgen -W "-name -id -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        delete)
            COMPREPLY=( $(compgen -W "-nameorid -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        examine)
            COMPREPLY=( $(compgen -W "-nameorid -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        interactive)
            COMPREPLY=( $(compgen -W "-cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        listentries)
            COMPREPLY=( $(compgen -W "-users -groups -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        listmax)
            COMPREPLY=( $(compgen -W "-cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        listowned)
            COMPREPLY=( $(compgen -W "-nameorid -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        membership)
            COMPREPLY=( $(compgen -W "-nameorid -supergroups -expandgroups -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        quit)
            COMPREPLY=( $(compgen -W "-cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        removeuser)
            COMPREPLY=( $(compgen -W "-user -group -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        rename)
            COMPREPLY=( $(compgen -W "-oldname -newname -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        setfields)
            COMPREPLY=( $(compgen -W "-nameorid -access -groupquota -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        setmax)
            COMPREPLY=( $(compgen -W "-group -user -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        sleep)
            COMPREPLY=( $(compgen -W "-delay -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
        source)
            COMPREPLY=( $(compgen -W "-file -cell -noauth -force -localauth -auth -encrypt -config -rxgk -help" -- "$cur") )
            ;;
    esac
}
complete -F _openafs_pts pts
