# Generated by generate_completions.pl --format bash
# Source this file to enable completions for udebug

_openafs_udebug() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "-server -port -long -help" -- "$cur") )
    return
}
complete -F _openafs_udebug udebug
