# Generated by generate_completions.pl --format bash
# Source this file to enable completions for vos

_openafs_vos() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "addsite backup backupsys changeaddr changeloc clone convertROtoRW copy create delentry dump endtrans examine listaddrs listpart listvldb listvol lock move offline online partinfo release remaddrs remove remsite rename restore setaddrs setfields shadow size status syncserv syncvldb unlock unlockvldb zap" -- "$cur") )
        return
    fi

    local sub="${COMP_WORDS[1]}"
    case "$sub" in
        addsite)
            COMPREPLY=( $(compgen -W "-server -partition -id -roid -valid -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        backup)
            COMPREPLY=( $(compgen -W "-id -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        backupsys)
            COMPREPLY=( $(compgen -W "-prefix -server -partition -exclude -xprefix -dryrun -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        changeaddr)
            COMPREPLY=( $(compgen -W "-oldaddr -newaddr -remove -force -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        changeloc)
            COMPREPLY=( $(compgen -W "-server -partition -id -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        clone)
            COMPREPLY=( $(compgen -W "-id -server -partition -toname -toid -offline -readonly -readwrite -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        convertROtoRW)
            COMPREPLY=( $(compgen -W "-server -partition -id -force -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        copy)
            COMPREPLY=( $(compgen -W "-id -fromserver -frompartition -toname -toserver -topartition -offline -readonly -live -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        create)
            COMPREPLY=( $(compgen -W "-server -partition -name -maxquota -id -roid -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        delentry)
            COMPREPLY=( $(compgen -W "-id -prefix -server -partition -dryrun -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        dump)
            COMPREPLY=( $(compgen -W "-id -time -file -server -partition -clone -omitdirs -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        endtrans)
            COMPREPLY=( $(compgen -W "-server -transaction -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        examine)
            COMPREPLY=( $(compgen -W "-id -extended -format -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        listaddrs)
            COMPREPLY=( $(compgen -W "-uuid -host -printuuid -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        listpart)
            COMPREPLY=( $(compgen -W "-server -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        listvldb)
            COMPREPLY=( $(compgen -W "-name -server -partition -locked -quiet -nosort -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        listvol)
            COMPREPLY=( $(compgen -W "-server -partition -fast -long -quiet -extended -format -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        lock)
            COMPREPLY=( $(compgen -W "-id -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        move)
            COMPREPLY=( $(compgen -W "-id -fromserver -frompartition -toserver -topartition -live -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        offline)
            COMPREPLY=( $(compgen -W "-server -partition -id -sleep -busy -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        online)
            COMPREPLY=( $(compgen -W "-server -partition -id -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        partinfo)
            COMPREPLY=( $(compgen -W "-server -partition -summary -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        release)
            COMPREPLY=( $(compgen -W "-id -force -f -force-reclone -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        remaddrs)
            COMPREPLY=( $(compgen -W "-uuid -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        remove)
            COMPREPLY=( $(compgen -W "-server -partition -id -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        remsite)
            COMPREPLY=( $(compgen -W "-server -partition -id -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        rename)
            COMPREPLY=( $(compgen -W "-oldname -newname -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        restore)
            COMPREPLY=( $(compgen -W "-server -partition -name -file -id -overwrite -offline -readonly -creation -lastupdate -nodelete -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        setaddrs)
            COMPREPLY=( $(compgen -W "-uuid -host -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        setfields)
            COMPREPLY=( $(compgen -W "-id -maxquota -clearuse -clearVolUpCounter -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        shadow)
            COMPREPLY=( $(compgen -W "-id -fromserver -frompartition -toserver -topartition -toname -toid -offline -readonly -live -incremental -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        size)
            COMPREPLY=( $(compgen -W "-id -partition -server -dump -time -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        status)
            COMPREPLY=( $(compgen -W "-server -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        syncserv)
            COMPREPLY=( $(compgen -W "-server -partition -dryrun -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        syncvldb)
            COMPREPLY=( $(compgen -W "-server -partition -volume -dryrun -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        unlock)
            COMPREPLY=( $(compgen -W "-id -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        unlockvldb)
            COMPREPLY=( $(compgen -W "-server -partition -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
        zap)
            COMPREPLY=( $(compgen -W "-server -partition -id -force -backup -cell -c -noauth -localauth -verbose -encrypt -noresolve -config -rxgk -help" -- "$cur") )
            ;;
    esac
}
complete -F _openafs_vos vos
